# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [2]:
import numpy as np
np.random.randint(10,22,22)




array([19, 19, 13, 12, 20, 14, 11, 20, 20, 20, 21, 19, 18, 16, 18, 17, 12,
       15, 17, 12, 11, 12])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [3]:
import numpy as np
arr=np.arange(1,50,2)
print("The length of the array is:", len(arr))
print("The numpy array is:", arr)





The length of the array is: 25
The numpy array is: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [4]:
import numpy as np
np.arange(4,7,3/27)




array([4.        , 4.11111111, 4.22222222, 4.33333333, 4.44444444,
       4.55555556, 4.66666667, 4.77777778, 4.88888889, 5.        ,
       5.11111111, 5.22222222, 5.33333333, 5.44444444, 5.55555556,
       5.66666667, 5.77777778, 5.88888889, 6.        , 6.11111111,
       6.22222222, 6.33333333, 6.44444444, 6.55555556, 6.66666667,
       6.77777778, 6.88888889])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [5]:
rand_array=np.random.rand(5,4)
np.round(rand_array,2)




array([[0.55, 0.74, 0.11, 0.82],
       [0.94, 0.68, 0.84, 0.84],
       [0.5 , 0.5 , 0.21, 0.68],
       [0.64, 0.33, 0.89, 0.89],
       [0.16, 0.12, 0.04, 0.11]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [6]:
import numpy as np
np.random.randint(5,16,(5,5))




array([[13, 14,  9,  9, 10],
       [14,  9,  6, 11, 11],
       [ 7,  6, 11, 13, 10],
       [13, 11,  9, 15, 11],
       [ 6,  8, 14, 11, 12]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [7]:


np.zeros(np.random.randint(20),dtype="int32")


array([0, 0, 0, 0, 0, 0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [8]:
r=np.random.randint(1,20)
c=np.random.randint(1,20)
print(r,c)
np.ones((r,c),dtype="float32")




5 8


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [9]:
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(mat)
print(mat.shape)
print(type(mat))
print(mat.dtype)




[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
(5, 5)
<class 'numpy.ndarray'>
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [10]:

x=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(x)
y=x.flatten()
mid_value=y[int(len(y)/2)]
print("the centre pixel of matrix is:",mid_value)
type(y)



[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
the centre pixel of matrix is: 3


numpy.ndarray

#### 10. Print the all the elements of 3rd row of the matrix

In [11]:
import numpy as np
print(mat[2,:])




[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [12]:
import numpy as np
print(mat[:,3])




[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [13]:
import numpy as np
print("1st corner matrix:", mat[0:2,0:2])
print("2nd corner matrix:", mat[0:2,3:5])
print("3rd corner matrix:", mat[3:5,0:2])
print("4th corner matrix:", mat[3:5,3:5])




1st corner matrix: [[ 9 25]
 [ 3 34]]
2nd corner matrix: [[34 45]
 [65  2]]
3rd corner matrix: [[ 7  8]
 [23 12]]
4th corner matrix: [[54  6]
 [ 5  8]]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [14]:
import numpy as np
m1=mat[0:2,2:4]
print(m1)
m2=mat[3:5,0:2]
print(m2)
m3=mat[2:5,2:5]
print(m3)




[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [15]:
import numpy as np
print(m1.reshape((1,4)))
print(m2.reshape((1,4)))
print(m3.reshape((1,9)))




[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [16]:
import numpy as np
print(np.concatenate((m1,m2),axis=0))
print(np.concatenate((m1,m2),axis=1))




[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
[[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [17]:
import numpy as np
print("addition result is:", m1+m2)
print("subtraction result is:", m1-m2)
print("division result is:", m1/m2)
print("multiplication result is:", m1*m2)





addition result is: [[57 42]
 [57 77]]
subtraction result is: [[43 26]
 [11 53]]
division result is: [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]
multiplication result is: [[350 272]
 [782 780]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [18]:
import numpy as np
add1=m3[1:3,0:2]
add=m1+add1
print(add)




[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [19]:

m1_mean=m1.mean(axis=0)
m1_mean=m1_mean.reshape(1,2)
m4=np.concatenate((m1,m1_mean),axis=0)
m4



array([[50. , 34. ],
       [34. , 65. ],
       [42. , 49.5]])

#### 19. Perform the matrix multiplication between m3 and m4

In [20]:

print(np.matmul(m3,m4))



[[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [21]:
matrix=np.random.random((5,4))
print("the matrix is:",x)
round_matrix=np.round(x,2)
print("rounded matrix is: ",round_matrix)


the matrix is: [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
rounded matrix is:  [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [22]:
runs=np.array([[54,60,10,65],[102,2,78,32],[2,110,1,92],[56,6,12,42],[12,8,22,11]]) 
balls=np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])
strikerate=(runs/balls)*100

print("average of each player in desc order")
print(np.sort(runs.mean(axis=1))[::-1],"\n")

print("average strike rate of each player in desc order")
print(np.sort(strikerate.mean(axis=1))[::-1],"\n")



average of each player in desc order
[53.5  51.25 47.25 29.   13.25] 

average strike rate of each player in desc order
[162.99554687  94.91125541  81.69675643  59.39926135  47.96296296] 



#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [23]:
marks=np.array([65,84,47,56,89,98,48,77,80,39])
passed=(marks>=50).sum()
failed=len(marks)-passed
print("number of stud passed :",passed)
print("number of stud failed :",failed)



number of stud passed : 7
number of stud failed : 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [28]:
marks=np.array([65,84,47,56,89,98,48,77,80,39])
pass_percent_bef=sum(marks>=50)*100/len(marks)
for i in range(len(marks)):
    if(marks[i]>44):
        if(marks[i]<50):
            marks[i]+=5
        elif(marks[i]>80):
            if(marks[i]+5>100):
                marks[i]=100
            else:
                marks[i]+=5
pass_percent_aft=sum(marks>=50)*100/len(marks)
print("marks\n{0}\nincrese in percentage\n{1}".format(marks,(pass_percent_aft-pass_percent_bef)))



marks
[ 65  89  52  56  94 100  53  77  80  39]
increse in percentage
20.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [25]:
import timeit

start = timeit.default_timer()
np_arr=np.arange(1,60000)
res1=((np_arr**2)+8)/np_arr
stop = timeit.default_timer()
print('Time: ', stop - start)

start = timeit.default_timer()
lst=list(range(1,60000))
res2=[]
for i in lst:
    res2.append(((i**2)+8)/i)
stop = timeit.default_timer()
print('Time: ', stop - start)






Time:  0.005657300000002863
Time:  0.08803729999999632


#### 25. Create a Github account and upload your solution with the short write-up on Numpy